source 'https://cdn.cocoapods.org/'
# source "https://github.com/CocoaPods/Specs.git"
#source "gogs@118.25.39.131:chat/CXSpec-iOS.git"
# source "http://bf27c7a857cb1ead51830c05a4acc852294ab493@git.ifeiyin.com:3000/iOS-Pods/CXSpec-iOS"
source "http://8f7dbbd63216f17fcbdb615da1ecfa924d299bcd@120.24.89.17:3000/iOS-Pods/CXSpec-iOS"






inhibit_all_warnings!

platform :ios, "9.0"
#s.ios.deployment_target = "6.0" 

target "HJLive" do
    # 压缩
    pod "AvoidCrash"
    pod "SSZipArchive"
    pod "SZTextView", "1.1.5"
    
    # LinkedME
    pod "LinkedME_LinkPage"

    #网络&数据&layout
    pod "AFNetworking"
    pod "WCDB"
    pod "Masonry"
    
    #svga & gif
    pod "SVGAPlayer"
    pod "FLAnimatedImage"
    pod "SDWebImage/GIF"
    
    #image
    pod "Qiniu"
    #alert
    pod "TYAlertController"

    # MVVM
    pod "libextobjc", " ~> 0.4"
    pod "ReactiveViewModel", "0.1.1"
    pod "ReactiveCocoa"
    
    #hud
    pod "MBProgressHUD", "~> 0.8"
   
    #YYKit
    pod "YYModel"
    pod "YYImage"
    pod "YYWebImage"
    pod "YYText", "~> 1.0.7"
    pod "YYCache", "~> 1.0.4"
    pod "YYCategories"
    
    #云信依赖
    pod "SDWebImage", "~> 4.2.3"
    pod "Toast", "~> 3.1.0"
    pod "M80AttributedLabel", "~> 1.6.3"
    
    #云信
    pod "NIMSDK_LITE"#, "~> 5.0.1"

    #声网
    pod "AgoraRtcEngine_iOS"
    
    #iap
    pod "IAPHelper"
    
    #下拉刷新
    pod "MJRefresh"
    
    #keyboard
    pod "IQKeyboardManager"  ,"6.5.3"
    pod "IQDropDownTextField"
    # 腾讯BUG管理
#    pod "Bugly"
   
    #动画
    pod "pop", "~> 1.0.10"
    
    pod "JPush"
    pod "VerifyCode"
    pod "SocketRocket"

   # pod "JXCategories" #, "0.8.8"
    
   # pod "JXKeychain", "0.0.1"
    pod "UMCAnalytics"


end

target "HJLiveTests" do
end

target "HJLiveUITests" do
end
