module.exports = {

    interest : {    //兴趣/爱好
        1 :'Going to Restaurants',
        2 : 'Cooking',
        3 : 'Travel',
        4 : 'Hiking/outdoor activities',
        5 : 'Dancing',
        6 : 'Watching movies',
        7 : 'Shopping',
        8 : 'Having pets',
        9 : 'Reading',
        10 : 'Sports/exercise',
        11 : 'Playing cards/chess',
        12 : 'Music/play instruments',
        prefix : 'interests_'
    },
    viewerInterest : {    //男士兴趣/爱好
        1 :'Dining Out',
        2 : 'Cooking',
        3 : 'Traveling',
        4 : 'Hiking/Outdoor Activities',
        5 : 'Dancing',
        6 : 'Watching Movies',
        7 : 'Shopping',
        8 : 'Having Pets',
        9 : 'Reading',
        10 : 'Sports/Workout',
        11 : 'Playing Cards/Chess',
        12 : 'Music/Play Instruments',
        prefix : 'interests_'
    },
    vetoAlbum : {
        '1' : 'Poor clarity.',
        '2' : 'Contains offensive / abusive content.',
        '3' : 'Contains unnecessary contents.',
        '4' : 'Contains illegal contents.',
        '5' : 'Your face must be clearly shown on the image.',
        '6' : 'Photo already in the album.',
        '7' : 'Other',
    },
    vetoAlbumVideo : {
        '1' : 'Video already in the album.',
        '2' : 'Broadcast does not show up during the video.',
        '3' : 'Video length does not meet the requirement.',
        '4' : 'Video looks alike with others.',
        '5' : 'Video is rotated/unplayable',
        '6' : 'Broadcaster’s dress-code/behavior does not meet the requirements',
        '7' : 'The appearances of broadcaster in video and photo do not match',
        '8' : 'Video is distorted',
        '9' : 'No sound in video / audio and video are not synchronized',
        '10' : 'Details of broadcaster in video do not match her profile',
        '11' : 'Other',
        '12' : 'Video resolution too low',
        '13' : 'Video contains text/watermarks which do not comply with our requirements',
        '14' : 'Video cover does not comply with our requirements',
    },
    shotsAlbum : {
        '1' : 'Poor clarity.',
        '2' : 'Contains offensive / abusive content.',
        '3' : 'Contains unnecessary contents.',
        '4' : 'Contains illegal contents.',
        '5' : 'Your face must be clearly shown on the image.',
        '6' : 'Photo duplicated.',
        '7' : 'Other',
    },
    shotsAlbumVideo : {
        '1' : 'Video already in the album.',
        '2' : 'Broadcast does not show up during the video.',
        '3' : 'Video length does not meet the requirement.',
        '4' : 'Video looks alike with others.',
        '5' : 'Video is rotated/unplayable',
        '6' : 'Broadcaster’s dress-code/behavior does not meet the requirements',
        '7' : 'The appearances of broadcaster in video and photo do not match',
        '8' : 'Video is distorted',
        '9' : 'No sound in video / audio and video are not synchronized',
        '10' : 'Details of broadcaster in video do not match her profile',
        '11' : 'Other',
        '12' : 'Video resolution too low',
        '13' : 'Video contains text/watermarks which do not comply with our requirements',
        '14' : 'Video cover does not comply with our requirements',
    },
    anchor_avatar:'http://192.168.88.17:8817/static/img/default-women-photo.png',
    user_avatar:'http://192.168.88.17:8817/static/img/default-man-photo.png',
    card_auth_reason_en : {//主播手持身份证審核否决原因
        1 : 'Your face is not clearly visible or it is unidentifiable.',
        2 : 'Your Application form for Broadcasting is not clearly visible or it is unidentifiable.',
        3 : 'The information in your Application form for Broadcasting is incorrect.',
        4 : 'Your Application form for Broadcasting did not show up in the video.',
        5 : 'Other'
    },
    showType:{
        1:'Singing',
        2:'Dancing',
        3:'Playing instrument',
        4:'Cooking',
        5:'Talk show',
        6:'Sports',
        7:'Outdoor activities',
        8:'Painting',
        9:'Others'
    },
    showCover:{
        1:'/app_images/deflaut_showcover/origin/singing.jpg',
        2:'/app_images/deflaut_showcover/origin/dancing.jpg',
        3:'/app_images/deflaut_showcover/origin/instrument.jpg',
        4:'/app_images/deflaut_showcover/origin/cooking.jpg',
        5:'/app_images/deflaut_showcover/origin/talkshow.jpg',
        6:'/app_images/deflaut_showcover/origin/sport.jpg',
        7:'/app_images/deflaut_showcover/origin/outdoor.jpg',
        8:'/app_images/deflaut_showcover/origin/painting.jpg',
        9:'/app_images/deflaut_showcover/origin/others.jpg',
    },
    showDenialReason:{
        1:'Contains offensive / abusive content.',
        2:'Contains unnecessary content.',
        3:'Contains illegal content.',
        4:'Poor clarity of show cover.',
        5:'Cover does not meet the requirement.',
        6:'Other',
    },
    showStatus:{
        3:'Finished',
        4:'Expired',
        5:'Cancelled',
    }
};